name: CI

on: [push]

jobs:
  Visual:
    runs-on: macos-latest
    env:
      CI: true
      DEVELOPER_DIR: /Applications/Xcode_11.2.app/Contents/Developer

    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm i -g expo-cli 
      - run: npm ci
      - name: run emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: npm run test:visual:ci
      # - run: open "${DEVELOPER_DIR}/Applications/Simulator.app"
      # - run: npm run test:visual:ci

