name: CI

on: [push]

jobs:
  Test:
    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci
      - run: npm run test:lint
      - run: npm run test:types
      - run: npm run test:unit

  Expo:
    runs-on: ubuntu-latest
    env:
      CI: true
    
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 3.x
          expo-cache: true
      - run: npm ci
      - run: expo diagnostics
      - run: expo doctor
      - run: ./test-expo-start.sh
      - run: ./test-expo-watch-mode.sh
  E2E:
    runs-on: macos-latest
    env:
      CI: true
    
    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: cd bin && mkdir Exponent.app && gunzip -c Exponent-2.14.0.tar.gz | tar xopf - -C Exponent.app
      - run: npm i -g detox-cli
      - run: npm ci
      - run: npm run test:e2e:ci
