name: CI

on: [push]

jobs:
  Visual:
    runs-on: macos-latest
    env:
      CI: true
      DEVELOPER_DIR: /Applications/Xcode_11.2.app/Contents/Developer

    steps:
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: xcrun instruments -w "iPhone 11 Pro (13.2) [" || true
      - run: npm i -g expo-cli 
      - run: npm ci
      - run: npm run test:visual:ci

